# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: ^.*\.ipynb
    - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      args: [--fast]  # Add this line to apply changes automatically
      exclude: ^.+\/migrations\/.+

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black", "--apply"]  # Add this line to apply changes automatically
